### PR TITLE
UWM-PATH: Site Config Base refresh - bug fix

### PR DESCRIPTION
**Pull request by chrisbeargroup**
@briantschu - I added this PR to the Develop branch as per the comment here - https://github.com/uwmweb/uwmcms/pull/9#issuecomment-309833785
There was some modules included in the last PR that were not needed.
This one should be fine.
CC - @Quevin

### CODE REVIEW

**Comment by briantschu** [comment]
Thanks for using the develop branch. 

It looks like this commit deletes all the config files. Is that the intention? I assumed by clean up, you meant were going to only remove the UUID from the files.

**Comment by chrisbeargroup** [comment]
I will try the drush @site cim here soon. The codebase on pathways.cmsdev.uwmedicine.org does not have the config *.yml files yet.
Thank you for your time.

**Comment by briantschu** [comment]
Looks like the deploy just finished (https://travis-ci.org/uwmweb/uwmcms/builds/245096435). I just checked and the `config/pathways` folder is now empty.

**Comment by chrisbeargroup** [comment]
@briantschu - I am committing. I did not have the updated *.yml files in the directory.

**Pull request merged**
