### PR TITLE
UWM-PATH: Adding Base Drupal Config for test

### PR DESCRIPTION
**Pull request by chrisbeargroup**
This is our base Config for a test.

### CODE REVIEW

**Comment by Quevin** [comment]
Hi @briantschu — is there a problem with this PR, does it need to be merged after the last PR?

PS - If not this AM, could we reach out for an off-schedule PR today?

Thanks!

cc: @chrisbeargroup

**Comment by briantschu** [comment]
Hi @Quevin: No problem at all -- I was under the impression you wanted to do the first test deploy at 1:00pm today, so I was waiting. I'll this now and let everything land in the `pathways` site as it's currently configured.

I'm going to change the base of this to the `develop` branch because I got an initial run of TravisCI set up.

**Comment by chrisbeargroup** [comment]
@briantschu 
The files committed on this Pull Request are not available to http://pathways.cmsdev.uwmedicine.org/ for a "drush cim" to import the "config" *.yml files for our test.
Has the "develop" branch updated the code base of the Pathways site?
Error: 
"The import failed due for the following reasons:                                   [error]
This import is empty and if applied would delete all of your configuration, so
has been rejected."

CC: @Quevin

**Comment by briantschu** [comment]
@Quevin and @chrisbeargroup 

Currently all three environments [dev, stage, prod] are running on the `develop-build` branch.

After deploying this PR, I tried to import the configuration to the prod server and database using `drush @pathways.uwmed.prod cim` using the option to overwrite the config from VCS and received the following output:

```
Drupal\Core\Config\ConfigImporterException: There were errors validating the config synchronization. in                                           [error]
Drupal\Core\Config\ConfigImporter->validate() (line 728 of /mnt/www/html/uwmed/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php).
The import failed due for the following reasons:                                                                                                  [error]
Site UUID in source storage does not match the target storage.
Unable to install the <em class="placeholder">uwmed_article</em> module since it does not exist.
Unable to install the <em class="placeholder">uwmed_core</em> module since it does not exist.
Unable to install the <em class="placeholder">uwmed_paragraphs</em> module since it does not exist.
```

I'll start some research now to see if there's a way around this. Happy to hop on a chat or call to talk through as well.

**Comment by chrisbeargroup** [comment]
I will cleanup the config export *yml files for the import.

**Pull request merged**
