### PR TITLE
UWM-HUD: Theme CSS / SASS changes

### PR DESCRIPTION
**Pull request by chrisbeargroup**
Had to delete my fork and redo the Git process.

### CODE REVIEW

**Comment by Quevin** [comment]
Hi @sodacrackers — is there something we can do to help move this forward? Thank you

**Comment by sodacrackers** [comment]
This commit should be behind a commit. Are you able to get latest, for the `composer.json` change in PR #79?  

If you get latest and push again, build tests should pass.

**Comment by chrisbeargroup** [comment]
@sodacrackers Can We get this PR Merged? Thank you.

**Comment by sodacrackers** [comment]
Many thanks.  I've merged and the deployment start in the next minutes.

**Pull request merged**
